#!/usr/bin/env python3
"""Generate Claude Code skill stubs from canonical .agents/skills files."""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

GENERATED_MARKER = "<!-- GENERATED BY sync_claude_skills.py; DO NOT EDIT -->"


def main() -> int:
    args = sys.argv[1:]
    prune = False
    repo_arg = "."

    for arg in args:
        if arg == "--prune":
            prune = True
        elif repo_arg == ".":
            repo_arg = arg
        else:
            print("error: expected at most one repo path plus optional --prune", file=sys.stderr)
            return 1

    repo = Path(repo_arg).resolve()
    source_root = repo / ".agents/skills"
    target_root = repo / ".claude/skills"

    if not source_root.is_dir():
        print(f"error: missing canonical skills root: {source_root}", file=sys.stderr)
        return 1

    if target_root.exists() and target_root.is_symlink():
        target_root.unlink()

    target_root.mkdir(parents=True, exist_ok=True)

    expected = set()

    for skill_dir in sorted(path for path in source_root.iterdir() if path.is_dir()):
        skill_file = skill_dir / "SKILL.md"
        if not skill_file.exists():
            continue

        expected.add(skill_dir.name)
        target_dir = target_root / skill_dir.name
        target_dir.mkdir(parents=True, exist_ok=True)
        target_file = target_dir / "SKILL.md"
        if target_file.exists() and not is_generated_stub(target_file):
            print(f"warning: preserving user-owned Claude skill stub: {target_file}", file=sys.stderr)
            continue
        target_file.write_text(render_stub(repo, skill_file), encoding="utf-8")

    for stale in sorted(path for path in target_root.iterdir() if path.is_dir()):
        if stale.name not in expected:
            if is_generated_skill_dir(stale):
                shutil.rmtree(stale)
            elif prune:
                print(
                    f"warning: --prune requested but preserving user-owned Claude skill dir: {stale}",
                    file=sys.stderr,
                )

    print("synced Claude skill stubs")
    return 0


def render_stub(repo: Path, skill_file: Path) -> str:
    content = skill_file.read_text(encoding="utf-8")
    frontmatter = extract_frontmatter(content)
    rel_path = skill_file.resolve().relative_to(repo).as_posix()

    body = [
        GENERATED_MARKER,
        "",
        "# Claude Compatibility Stub",
        "",
        "This file exists so Claude Code can discover this project skill.",
        "",
        "Canonical skill content lives at:",
        "",
        f"- `{rel_path}`",
        "",
        "Read the canonical skill file before using this skill.",
        "",
        "Do not edit this stub manually. Regenerate it from the canonical `.agents/skills/` tree.",
        "",
    ]

    if frontmatter:
        return f"{frontmatter}\n\n" + "\n".join(body)
    return "\n".join(body)


def extract_frontmatter(content: str) -> str:
    if not content.startswith("---\n"):
        return ""
    end = content.find("\n---", 4)
    if end == -1:
        return ""
    return content[: end + 4]


def is_generated_stub(path: Path) -> bool:
    try:
        content = path.read_text(encoding="utf-8")
    except OSError:
        return False
    return GENERATED_MARKER in content or "# Claude Compatibility Stub" in content


def is_generated_skill_dir(path: Path) -> bool:
    entries = list(path.iterdir())
    if not entries:
        return False
    if len(entries) != 1:
        return False
    stub = path / "SKILL.md"
    return stub.exists() and is_generated_stub(stub)


if __name__ == "__main__":
    raise SystemExit(main())
